
# allSteps	currentStep	frequency	frequencyBegin	frequencyValue	period	periodTo	periodFrom	rootStepToExport
false	true	false	0	0	false	0	0	false
# subject	variables	exportAll	ids
SafeTree	{SafeTree-carbonBranches;SafeTree-carbonCoarseRootSenAnnual;SafeTree-carbonCoarseRoots;SafeTree-carbonFineRootSenAnnual;SafeTree-carbonFineRoots;SafeTree-carbonFoliageMax;SafeTree-carbonLabile;SafeTree-carbonStem;SafeTree-carbonAllocToGrowthAnnual;SafeTree-carbonLeavesSenescenceAnnual;SafeTree-leafAreaMax;SafeTree-nitrogenStressSpring;SafeTree-nitrogenStressSummer;SafeTree-nitrogenUptakeAnnual;SafeTree-parInterceptedAnnual;SafeTree-maxRootDistanceOnCropLine;SafeTree-maxRootDistanceOnTreeLine;SafeTree-rootingDepth;SafeTree-totalRootVolume;SafeTree-totalRootVolumePerLayer;SafeTree-dbh;SafeTree-height;SafeTree-interceptedRainAnnual;SafeTree-waterStressSpring;SafeTree-waterStressSummer;SafeTree-waterUptakeAnnual}	true	{}
